ALIASES = {
    "A.D.": "C.E.",
    "AD": "CE",
    "Anchor": "anchor",
    "B.C.": "B.C.E.",
    "BC": "BCE",
    "C": "topics",
    "Cite book": "cite-book",
    "Cuneiform refs": "R:Cuneiform refs",
    "EtymOnLine": "R:Online Etymology Dictionary",
    "JLect": "R:JLect",
    "L": "link",
    "Mallinckrodt": "R:Mallinckrodt",
    "Molina1555": "R:es:Molina1555",
    "NPED": "R:fa:Hayyim",
    "NPLarousse": "R:NPLarousse",
    "SUB": "sub",
    "SUP": "sup",
    "Shin'yaku Kegonky\u014d Ongi Shiki": "R:Shin'yaku Kegonky\u014d Ongi Shiki",
    "U": "cap",
    "Underline": "underline",
    "User:Catonif/RQ:mxi:Kharja": "RQ:mxi:Kharja",
    "VDEWb": "R:VDEWb",
    "Willett et al. 2016": "R:Willett et al. 2016",
    "YM1987": "R:nv:Young and Morgan 1987",
    "YM1992": "R:nv:Young and Morgan 1992",
    "a": "accent",
    "a.": "ante",
    "abbr of": "abbreviation of",
    "abbrev of": "abbreviation of",
    "acro": "acronym",
    "acro of": "acronym of",
    "af": "affix",
    "afb:Hamdi": "R:afb:Qafisheh",
    "alt case": "alternative case form of",
    "alt case form": "alternative case form of",
    "alt case form of": "alternative case form of",
    "alt case of": "alternative case form of",
    "alt form": "alternative form of",
    "alt form of": "alternative form of",
    "alt of": "alternative form of",
    "alt sp": "alternative spelling of",
    "alt sp of": "alternative spelling of",
    "alt spell": "alternative spelling of",
    "alt spelling of": "alternative spelling of",
    "alt typ": "alternative typography of",
    "altcase": "alternative case form of",
    "altform": "alternative form of",
    "altform of": "alternative form of",
    "altsp": "alternative spelling of",
    "altspell": "alternative spelling of",
    "angbr": "orthography",
    "apoc of": "apocopic form of",
    "arch form": "archaic form of",
    "arch sp": "archaic spelling of",
    "att": "attention",
    "attn": "attention",
    "aug of": "augmentative of",
    "b-f": "back-formation",
    "back-form": "back-formation",
    "backform": "back-formation",
    "backformation": "back-formation",
    "bf": "back-formation",
    "bor": "borrowed",
    "c": "topics",
    "cal": "calque",
    "cat": "categorize",
    "cens sp": "censored spelling of",
    "chhoetaigi": "R:nan-hbl:chhoetaigi",
    "cite MLLM 1976": "R:MLLM 1976",
    "cite book": "cite-book",
    "cite-text": "cite-book",
    "cleanup": "rfc",
    "clip": "clipping",
    "clip of": "clipping of",
    "cln": "catlangname",
    "clq": "calque",
    "cog": "cognate",
    "coin": "coinage",
    "coined": "coinage",
    "colour panel": "color panel",
    "com": "compound",
    "comb form": "combining form of",
    "comd of": "comparative of",
    "comparative degree of": "comparative of",
    "compound+": "com+",
    "con": "confix",
    "conj of": "inflection of",
    "contr": "contraction",
    "contr of": "contraction of",
    "cx": "context",
    "date-def": "defdate",
    "dated form": "dated form of",
    "dated sp": "dated spelling of",
    "datedef": "defdate",
    "dbt": "doublet",
    "def-date": "defdate",
    "delib missp": "deliberate misspelling of",
    "delib missp of": "deliberate misspelling of",
    "der": "derived",
    "der?": "undefined derivation",
    "deverbative": "deverbal",
    "dim of": "diminutive of",
    "dmissp": "deliberate misspelling of",
    "dmissp of": "deliberate misspelling of",
    "en-adjective": "en-adj",
    "en-adverb": "en-adv",
    "en-pronoun": "en-pron",
    "en-prop": "en-proper noun",
    "en-proper-noun": "en-proper noun",
    "en-propn": "en-proper noun",
    "en-usage-verb-particle-solid": "U:en:verb particle solid",
    "es-adjective": "es-adj",
    "es-adverb": "es-adv",
    "es-past-participle": "es-past participle",
    "es-prop": "es-proper noun",
    "euph form": "euphemistic form of",
    "example?": "rfex",
    "fa sp": "filter-avoidance spelling of",
    "femeq": "female equivalent of",
    "fo-lit-FED": "R:fo-lit-FED",
    "freq of": "frequentative of",
    "geoportail": "R:fr:Geoportail",
    "gl": "gloss",
    "gl-lite": "gloss-lite",
    "grasskey": "R:Grasskey",
    "honor alt case": "honorific alternative case form of",
    "honour alt case": "honorific alternative case form of",
    "i": "qualifier",
    "ic": "IPAchar",
    "img": "multiple images",
    "inf form": "informal form of",
    "infl of": "inflection of",
    "inh": "inherited",
    "init": "initialism",
    "init of": "initialism of",
    "ipachar": "IPAchar",
    "is-lit-IOD": "R:is:\u00cdslensk-ensk or\u00f0ab\u00f3k 1989",
    "ja-r/syn": "ja-r",
    "kip-un": "R:nan-hbl:kip-finals",
    "klamer 1998": "R:xbr:klamer 1998",
    "ko-inline": "ko-l",
    "l": "link",
    "lb": "label",
    "lbl": "label",
    "lbor": "learned borrowing",
    "lg": "glossary",
    "literally": "lit",
    "m": "mention",
    "m-g": "mention-gloss",
    "mg": "mention-gloss",
    "missp": "misspelling of",
    "missp of": "misspelling of",
    "multiple image": "multiple images",
    "n-g": "non-gloss",
    "ncog": "noncognate",
    "ncog-lite": "cog-lite",
    "ng": "non-gloss",
    "ng-lite": "n-g-lite",
    "ngd": "non-gloss",
    "nl": "nonlemma",
    "nom of": "nominalization of",
    "non-gloss definition": "non-gloss",
    "non-lemma": "nonlemma",
    "noncog": "noncognate",
    "noncog-lite": "cog-lite",
    "nonlemmas": "nonlemma",
    "nowrap": "nobr",
    "nstd form": "nonstandard form of",
    "nstd sp": "nonstandard spelling of",
    "numberbox": "number box",
    "numbox": "number box",
    "obs form": "obsolete form of",
    "obs form of": "obsolete form of",
    "obs sp": "obsolete spelling of",
    "obs sp of": "obsolete spelling of",
    "obs typ": "obsolete typography of",
    "only in": "only used in",
    "onom": "onomatopoeic",
    "onomatopeic": "onomatopoeic",
    "onomatopoeia": "onomatopoeic",
    "orth": "orthography",
    "ortho": "orthography",
    "pcal": "partial calque",
    "pclq": "partial calque",
    "pl": "pseudo-loan",
    "pl-prop": "pl-proper noun",
    "plural": "plural of",
    "pre": "prefix",
    "pron sp": "pronunciation spelling of",
    "pron sp of": "pronunciation spelling of",
    "pron spelling of": "pronunciation spelling of",
    "pseudoloan": "pseudo-loan",
    "psm": "phono-semantic matching",
    "pt-cite-peregrina\u00e7am": "RQ:Peregrina\u00e7am",
    "q": "qualifier",
    "qf": "qualifier",
    "qual": "qualifier",
    "qualifier-lite": "q-lite",
    "r:ABVD": "R:ABVD",
    "r:AndhraBharati": "R:AndhraBharati",
    "r:CLR": "R:CLR",
    "r:Cre-A 1992": "R:Cre-A 1992",
    "r:Gravina Dict": "R:mfh:Gravina Dict",
    "r:Useinov 2007": "R:Useinov 2007",
    "r:az:Islamov": "R:az:Islamov",
    "r:cop:Kircher": "R:cop:Kircher",
    "r:kum:\u00c7\u0131nar:2019": "R:kum:\u00c7\u0131nar:2019",
    "r:lmy:geirnaert-martin": "R:lmy:geirnaert-martin",
    "r:lmy:rina": "R:lmy:rina",
    "r:lmy:verdizade19b": "R:lmy:verdizade19b",
    "r:obastan": "R:az:Obastan",
    "r:qwm:Tavkul": "R:qwm:Tavkul",
    "r:sv:karp": "R:sv:karp",
    "r:ta:QCC Glossary": "R:ta:QCC Glossary",
    "r:tr:Lewis:1999": "R:tr:Lewis:1999",
    "r:tr:yavuzarslan": "R:tr:yavuzarslan",
    "r:tr:yavuzarslan/documentation": "R:tr:yavuzarslan/documentation",
    "r:trk-oat:D\u00f6rfer 1969": "R:trk-oat:D\u00f6rfer 1969",
    "r:trk-oat:abd\u00fclb\u00e2k\u00ee-1934": "R:trk-oat:abd\u00fclb\u00e2k\u00ee-1934",
    "r:trk:Stachowski": "R:trk:Stachowski",
    "r:trk:Tekin 1994": "R:trk:Tekin 1994",
    "r:trk:Tekin:1995": "R:trk:Tekin:1995",
    "r:trk:oat:abd\u00fclb\u00e2k\u00ee-1934": "R:trk-oat:abd\u00fclb\u00e2k\u00ee-1934",
    "r:tyz:tdcnt": "R:tyz:tdcnt",
    "r:wew:loli": "R:wew:loli",
    "r:xqa:DLT": "R:xqa:DLT",
    "rare form": "rare form of",
    "rare sp": "rare spelling of",
    "rare sp of": "rare spelling of",
    "rare spelling": "rare spelling of",
    "rdp": "reduplication",
    "redup": "reduplication",
    "request for etymology": "rfe",
    "rfety": "rfe",
    "rfetym": "rfe",
    "rfq-sense": "rfquote-sense",
    "rfusex": "rfex",
    "roa-opt-cite-cantigas": "RQ:roa-opt:Cantigas de Santa Maria",
    "rom of": "romanization of",
    "ru-pre-reform-1918": "ru-pre-reform",
    "s": "sense",
    "sc": "script",
    "serial comma": ",",
    "sic.": "sic",
    "sid": "senseid",
    "sl": "semantic loan",
    "slbor": "semi-learned borrowing",
    "small caps": "smallcaps",
    "smc": "smallcaps",
    "ssb": "R:nn:SSB",
    "stand sp": "standard spelling of",
    "suf": "suffix",
    "sup sp": "superseded spelling of",
    "supd of": "superlative of",
    "superscript": "sup",
    "surf": "surface analysis",
    "surface etymology": "surface analysis",
    "swp": "slim-wikipedia",
    "syn": "synonyms",
    "syn of": "synonym of",
    "sync": "syncopic form",
    "thcwd": "R:nan-hbl:thcwd",
    "thcwda": "R:nan-hbl:thcwda",
    "thcwdq": "R:nan-hbl:thcwdq",
    "thub": "translation only",
    "tlb": "term-label",
    "top": "topics",
    "topic": "topics",
    "transclude sense": "transclude",
    "translation hub": "translation only",
    "translit": "transliteration",
    "ubor": "unadapted borrowing",
    "uder": "undefined derivation",
    "unc": "uncertain",
    "uncom form": "uncommon form of",
    "uncom form of": "uncommon form of",
    "uncom sp": "uncommon spelling of",
    "uncom sp of": "uncommon spelling of",
    "uncom spelling": "uncommon spelling of",
    "uncom spelling of": "uncommon spelling of",
    "uncommon form": "uncommon form of",
    "uncommon sp": "uncommon spelling of",
    "uncommon sp of": "uncommon spelling of",
    "uncommon spelling": "uncommon spelling of",
    "univ": "univerbation",
    "unk": "unknown",
    "upright": "noitalic",
    "usex": "ux",
    "vernacular": "vern",
    "was FWOTD": "was fwotd",
    "webofscience": "R:is:webofscience",
    "wikipediapar": "w",
    "wp": "wikipedia",
    "zh-abbrev": "zh-short",
    "zh-alt-term": "zh-altterm",
    "zh-erhua form of": "cmn-erhua form of",
    "zh-misspelling": "zh-misspelling of",
    "zh-used": "zh-used in",
    "\u2026": "..."
}
